[package]
name = "oxidizr"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = "4.5.17"
env_logger = "0.11.5"
hex = "0.4.3"
log = "0.4.22"
openssl = "0.10.66"
ring = "0.17.8"
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde_json = "1.0.128"
